name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy using SSH and password auth
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: aravconray
          SSH_HOST: 34.55.231.152
          GIT_TOKEN: ${{ secrets.SSH_TOKEN }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            set -e
            
            cd ~/portfolio

            git pull https://angadsudan:$GIT_TOKEN@github.com/AngadSudan/Developer-Portfolio.git main

            ls

            npm install

            npm run build

            # Remove old frontend and copy new one
            sudo rm -rf /var/www/portfolio/*

            sudo cp -r dist/* /var/www/portfolio/

            cd backend

            npm install

            pm2 restart portfolio-backend

            sudo systemctl restart nginx
          EOF
