name: Deploy to staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy using password auth
        env:
          SSH_PASSWORD: ${{ secrets.password }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no aravconray@35.184.235.218 << 'EOF' && ls
            cd portfolio && 
            git pull https://angadsudan:${{secrets.sshToken}}@github.com/AngadSudan/Developer-Portfolio.git main && ls && npm i && npm run build && cd backend &&
             pwd && 
            npm install && pm2 restart portfolio-backend
          EOF
